### PR TITLE
Update translation.js

### PR DESCRIPTION
**Pull request by Airon90**
- Alphabetical reorder translation by code
- Added Esperanto (eo) translation
- Corrected (horrible) typos in Italian (it) translation

### CODE REVIEW

**Comment by willyaranda** [comment]
There is a pending PR by @Timmaks on #91 that I need to review and merge that changes how we do translations.

So, I'm going to close this, and I will point you when the merge has concluded, so you can use it on transifex to translate.

**Comment by Airon90** [comment]
BTW why don't you merge my translation so that my new translation and my corrections are on Transifex?

**Comment by willyaranda** [comment]
@Timmaks would you like to help on moving the translation to transifex? If so, I can merge it.

**Comment by Timmaks** [comment]
The move to transifex is on my to do list.  I want to use the versions that are in my pull request as a start. I will port this pull request to my repro so when transifex is active this changes are there.

**Comment by Airon90** [comment]
Thank you very much, Timmask. Tell me when I can delete my branch! :D

**Comment by Timmaks** [comment]
@Airon90 your changes of "it" and "eo" are in transifex 

https://www.transifex.com/projects/p/openwapp/language/it/
https://www.transifex.com/projects/p/openwapp/language/eo/

please check if everything is ported ok

**Comment by Airon90** [comment]
I will check the ranslations upstream. Thank you very much, @Timmaks!

**Pull request closed without merging**
