### PR TITLE
Various translation improvements and fixes for Brazilian Portuguese

### PR DESCRIPTION
**Pull request by jesobreira**
Brazilian Portuguese translation is confusing and hard to understand. This patch modifies the text strings, so it will be easier to understand. I rewrote many wrong strings (due to lack of grammar rules following and/or hardness to understand), fixed the spelling of some words as well as fixed a bug that, in the registration screen, it was showing (in portuguese and brazilian portuguese):

> Você tem um {{país}} número de telefone.
("You have a {{country}} telephone number.")

While it should be:
> Você tem um Brasil número de telefone

(This example showed just fixing the tag, from `{{país}}` to `{{country}}`. This sentence is bad-formed, so I rewrote it completely on the pt-BR translation.)

Please note that, while pt-BR translation was almost completely rewritten, pt-PT translation had just the tag fixing (above) change, since I don't know pt-PT (it's basically two different languages, similar in some grammar rules, but very different in other aspects).

### CODE REVIEW

**Comment by Timmaks** [comment]
Hi thanks for the changes. But all translations are done in transifex, https://www.transifex.com/mozilla-tech-evangelism/openwapp/. I can  appy this pul, request but you need to change it also in transifex, otherwise it will be overwritten with the next sync

**Comment by Timmaks** [comment]
Thanks, I merged your changes but please make this changes also in transifex

**Comment by jesobreira** [comment]
Fine, thank you! I just requested to join the OpenWapp translation and I'll make these changes in transifex once I'm accepted on it.

**Comment by Timmaks** [comment]
Great you are now accepted :-)

**Comment by jesobreira** [comment]
It's done, I just made the changes on Transifex! :smiley:

**Pull request merged**
