### PR TITLE
Translation of permissions into German

### PR DESCRIPTION
**Pull request by naitsirch**
I have translated the permission descriptions of the `app/manifest.webapp` into German.

### CODE REVIEW

**Comment by willyaranda** [comment]
Hi,

thanks for this. But last time I sent the app to the marketplace, I got some warnings about permissions not valid inside `manifest` translations.

I will check and merge if it makes sense.

Thanks!

**Comment by Timmaks** [comment]
this is ok to do the only thing is that the locale for German is de and not de-DE. i don know if this is causing the problems you saw

**Comment by naitsirch** [comment]
Okay, I have changed the German locale to "de". Hope this helps

**Comment by willyaranda** [comment]
I can merge this, but it's not used right now.

**Pull request merged**
