### PR TITLE
Added plural forms. Solves #137 - second point and #192 (which mentioned other strings)

### PR DESCRIPTION
**Pull request by bidaian**
This pull request adds plural forms. I checked (for messages and conversations) it and it works and is backwards compatible. I'm using it right now.

Nothing breaks, if the locale has the old, non pluralized translations, they are used as before, no changes. If the plural forms have been translated, then they are used. I checked with eo (my current language), en-US and es.

### CODE REVIEW

**Comment by Timmaks** [comment]
Thanks, will test en apply it as soon as possible

**Comment by Timmaks** [comment]
Looks good, can you change the localization of en and es on transifex to reflect this changes (en-us should be updated automatically)

**Comment by bidaian** [comment]
en-us hasn't changed yet. I'll check later. Is there a way for you to push the source to transifex?

**Comment by Timmaks** [comment]
There is a fixed time when recourses are synced and i am not sure when. If it is not synced tomorrow, 24 hours after the change, i will sync it manually

**Comment by bidaian** [comment]
Ok, done! I've translated eo and es.

**Comment by willyaranda** [comment]
@bidaian where have you translated `es`?

**Comment by Timmaks** [comment]
@willyaranda he did it in transifex as i requested

**Comment by bidaian** [comment]
Any idea on when this will make it to MarketPlace?

**Comment by willyaranda** [comment]
I need to properly download the files and test that everything is working.

**Pull request merged**
